"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // General
        "portal_access": "Portal Access",
        "prof_med_intel": "Professional Medical Intelligence",
        "access_portal": "Access Portal",
        "system_secure_online": "System Secure & Online",
        "enter_username": "Enter username",
        "get_started": "Get Started",
        "live_experience": "Live Experience",
        "features": "Features",
        "about_us": "About Us",
        "contact": "Contact",
        "login": "Login",
        "logout": "Logout",
        "search_placeholder": "Search patients, employees...",
        "demo": "Demo",
        "v2_pre_release": "v2.0 Pre-Release",
        "innovation_first": "Innovation First",
        "core_capabilities": "Core Capabilities",
        "experience_edge": "Experience the Edge",
        "interactive_experience": "The Interactive Experience",
        "doctors_love": "Explore the interface that doctors love.",
        "operations": "Operations",
        "support_center": "Support Center",
        "terms_service": "Terms of Service",
        "all_rights_reserved": "© 2026 MedCRM Elite Intelligence. All Rights Reserved.",
        "global_standards": "Global Healthcare standards",
        "super_speed": "Super Speed",
        "super_speed_desc": "Real-time system with unmatched performance to save your time.",
        "absolute_security": "Absolute Security",
        "absolute_security_desc": "Patient data encryption at the highest international standards.",
        "smart_integration_desc": "Direct link with WhatsApp for seamless and permanent communication with your patients.",
        "active_clinic": "Active Clinic",
        "customer_satisfaction": "Customer Satisfaction",
        "doctor_focus": "At Rawad Al-Mati, we believe you should focus on your vision, not the paperwork. We build smart systems that power your growth with precision.",
        "innovators_team": "We are your partners in success, crafting digital growth stories from A to Z.",
        // Feature Bento Grid
        "feat_bento_title": "The Intelligence Layer",
        "feat_bento_subtitle": "MedCRM is more than a database; it's a proactive partner in your clinic's success.",
        "feat_unified_inbox_title": "Unified Communication Hub",
        "feat_unified_inbox_desc": "Receive and manage WhatsApp, Facebook, and Instagram messages in one centralized screen. No more switching apps.",
        "feat_lead_capture_title": "Automated Lead Capture",
        "feat_lead_capture_desc": "Convert comments and messages into leads with a single click. Track exactly where your patients are coming from.",
        "feat_archiving_title": "Unified Digital Archive",
        "feat_archiving_desc": "All client data and history centralzed in one high-security portal for immediate access.",
        "feat_analytics_title": "Smart Decision Reporting",
        "feat_analytics_desc": "Get a comprehensive view of performance to make data-driven clinical and administrative decisions.",
        "feat_automation_title": "Process Automation",
        "feat_automation_desc": "Reduce manual work and save time by automating repetitive tasks and follow-ups.",
        "feat_team_sync_title": "Elite Team Coordination",
        "feat_team_sync_desc": "Perfect alignment between sales, marketing, and medical staff for a cohesive patient journey.",
        // Landing Page
        "hero_title_1": "The Operating System for",
        "hero_title_2": "Modern Medicine",
        "hero_subtitle": "Elevate your clinic with a sophisticated intelligence layer. Manage patients, staff, and operations with unprecedented precision and style.",
        "trusted_by": "Trusted by Leading Medical Centers",
        "features_title": "Unrivaled Power, Artfully Delivered.",
        "features_subtitle": "MedCRM isn't just a tool; it's a competitive advantage for your practice.",
        // Features Section
        "feat_patients_title": "Patient Management",
        "feat_patients_desc": "Centralized patient records with clinical history and precision tracking.",
        "feat_staff_title": "HR & Staff",
        "feat_staff_desc": "Control access and monitor performance of your elite medical team.",
        "feat_localization_title": "Local & Multi-lingual",
        "feat_localization_desc": "Seamless support for Arabic and English with RTL precision.",
        // About Us
        "about_narrative": "Rawad Al-Mati Company was established to be the primary technology and marketing partner for medical and smart facilities in the Kingdom of Saudi Arabia.",
        "about_vision_title": "Our Vision",
        "about_vision_desc": "To be the digital backbone for the Kingdom's most prestigious and successful centers.",
        "about_values_title": "Medical Excellence",
        "about_values_desc": "Every pixel and line of code is optimized for medical-grade reliability.",
        // Social
        "follow_us": "Follow the Future of Medicine",
        "whatsapp_connect": "Direct WhatsApp Line",
        "instagram_story": "Clinical Excellence on Instagram",
        "telegram_updates": "Secure Laboratory Updates",
        // Dashboard
        "dashboard": "Dashboard",
        "employees": "Employees",
        "patients": "Patients",
        "whatsapp": "WhatsApp",
        "activity": "Activity",
        "settings": "Settings",
        // Dashboard Stats
        "total_patients": "Total Patients",
        "active_employees": "Active Employees",
        "appointments_today": "Appointments Today",
        "revenue_monthly": "Revenue (Monthly)",
        "revenue_weekly": "Revenue (Weekly)",
        "revenue_daily": "Revenue (Daily)",
        "view_all": "View All",
        "no_recent_activity": "No recent activity recorded.",
        "welcome_command_center": "Welcome to your medical command center.",
        "intelligence_core": "Intelligence Core",
        "medical_alerts": "Medical Alerts",
        "no_alerts": "No critical alerts currently.",
        "patient_growth": "Patient Growth & Activity",
        "initializing_data": "Initializing Data Streams...",
        "initializing_data_sub": "Please wait while we synchronize your clinical records.",
        // Patients Module
        "patients_title": "Patients",
        "patients_subtitle": "Manage patient records and track their health status.",
        "search_patients": "Search patients...",
        "patient_list": "Patient List",
        "add_new_patient": "Add New Patient",
        "add_patient": "Add Patient",
        "edit_patient": "Edit Patient",
        "patient_details": "Patient Details",
        "all_types": "All Types",
        "individual": "Individual",
        "company": "Company",
        "archive_empty": "Archive Empty",
        "patient_name": "Patient Name",
        "patient_type": "Patient Type",
        "phone_number": "Phone Number",
        "email_address": "Email Address",
        "whatsapp_number": "WhatsApp Number",
        "address": "Address",
        "gender": "Gender",
        "male": "Male",
        "female": "Female",
        "birth_date": "Birth Date",
        "status": "Status",
        "new": "New",
        "admitted": "Admitted",
        "discharged": "Discharged",
        "under_treatment": "Under Treatment",
        "recovered": "Recovered",
        "full_name": "Full Name",
        "patient_added_success": "Patient added successfully!",
        "adding": "Adding...",
        "save": "Save",
        "chat": "Chat",
        "details": "Details",
        "data_management": "Data Management",
        "backup_subtitle": "Securely backup and restore your system data.",
        "export_data": "Export Data",
        "export_desc": "Create a full snapshot of your Patients, Employees, and Activity Logs.",
        "import_desc": "Restore data from a previously generated backup file.",
        "download_backup": "Download Backup",
        "restore_data": "Restore Data",
        "restoring": "Restoring...",
        "generating": "Generating...",
        // Employees Module
        "employees_title": "Employees",
        "employees_subtitle": "Manage your medical staff and team members.",
        "search_employees": "Search by name, role, or phone...",
        "add_employee": "Add Employee",
        "edit_employee": "Edit Employee",
        "backup_restore": "Backup & Restore",
        "no_employees_found": "No employees found. Click 'Add Employee' to create one.",
        "role": "Role",
        "department": "Department",
        "username": "Username",
        "password": "Password",
        "login_credentials": "Login Credentials",
        "general_dept": "General",
        "active": "Active",
        "inactive": "Inactive",
        "disable_access": "Disable Access",
        "enable_access": "Enable Access",
        "edit_details": "Edit Details",
        "employee_added_success": "Employee added successfully!",
        "employee_updated_success": "Employee updated successfully!",
        "saving": "Saving...",
        "backup_mgmt": "Manage your employee data",
        "export_json": "Export to JSON",
        "import_json": "Import from JSON",
        "exporting": "Exporting...",
        "importing": "Importing...",
        "clear_all_employees": "Clear All Employees",
        "important_notes": "Important Notes",
        "export_note": "Export creates a JSON backup file",
        "import_note": "Import merges data (updates existing, adds new)",
        "clear_note": "Clear All permanently deletes all employees",
        "export_success": "Successfully exported employees",
        "import_success": "Import complete",
        "clear_success": "Deleted employees",
        "invalid_json": "Invalid JSON file or import failed",
        // Settings Module
        "settings_title": "Settings",
        "settings_subtitle": "Manage your application preferences and system configuration.",
        "lang_localization": "Language & Localization",
        "lang_localization_desc": "Set your preferred language and regional settings.",
        "system_lang": "System Language",
        "choose_pref_lang": "Choose your preferred interface language",
        "date_format": "Date Format",
        "date_format_us": "MM/DD/YYYY (US)",
        "date_format_eg": "DD/MM/YYYY (UK/Egypt)",
        "date_format_iso": "YYYY-MM-DD (ISO)",
        "time_date_settings": "Time & Date Settings",
        "time_date_desc": "Configure time display and timezone preferences.",
        "timezone": "Timezone",
        "cairo_tz": "Cairo (GMT+2) - Egypt",
        "utc_tz": "UTC (GMT+0)",
        "ny_tz": "New York (EST)",
        "london_tz": "London (GMT)",
        "dubai_tz": "Dubai (GST)",
        "clock_display": "Clock Display",
        "12_hour": "12 Hour (AM/PM)",
        "24_hour": "24 Hour",
        "notifications": "Notifications",
        "notifications_desc": "Control how you receive alerts and updates.",
        "whatsapp_notif": "WhatsApp Notifications",
        "whatsapp_notif_desc": "Receive appointment reminders via WhatsApp",
        "email_notif": "Email Notifications",
        "email_notif_desc": "Get daily summary reports via email",
        "appearance": "Appearance",
        "appearance_desc": "Customize the look and feel of your workspace.",
        "theme_mode": "Theme Mode",
        "light_mode": "Light Mode",
        "dark_mode": "Dark Mode",
        "system_auto": "System Auto",
        "security_privacy": "Security & Privacy",
        "security_privacy_desc": "Manage your account security settings.",
        "change_password": "Change Password",
        "two_factor": "Two-Factor Authentication",
        "active_sessions": "Active Sessions",
        "data_mgmt": "Data Management",
        "data_mgmt_desc": "Backup and manage your clinic data.",
        "export_excel": "Export All Data (Excel)",
        "import_data": "Import Data",
        "clear_data": "Clear All Data (Dangerous)",
        // Form Buttons / UI
        "save_changes": "Save Changes",
        "cancel": "Cancel",
        "apply": "Apply",
        "confirm": "Confirm",
        "delete": "Delete",
        "loading": "Loading...",
        "whatsapp_messages": "WhatsApp Messages",
        "manage_whatsapp_desc": "Manage patient inquiries and messages from WhatsApp.",
        "open_whatsapp_web": "Open WhatsApp Web",
        "clinic_whatsapp_num": "Clinic WhatsApp Number",
        "patients_reach_at": "Patients can reach you at:",
        "open_chat": "Open Chat",
        "total_messages": "Total Messages",
        "unread": "Unread",
        "read": "Read",
        "avg_response_time": "Avg Response Time",
        "all_messages": "All Messages",
        "unread_only": "Unread Only",
        "read_only": "Read Only",
        "filter": "Filter",
        "recent_messages": "Recent Messages",
        "reply_on_whatsapp": "Reply on WhatsApp",
        "mark_as_read": "Mark as Read",
        "load_more_messages": "Load More Messages",
        "whatsapp_api_integrate": "How to integrate WhatsApp Business API",
        "whatsapp_api_desc": "To receive real messages from patients, you need to integrate WhatsApp Business API. Contact your developer to set up webhooks and connect this page to your WhatsApp Business account.",
        "system_activity": "System Activity",
        "monitor_activity_desc": "Monitor recent actions and system events in real-time.",
        "todays_events": "Today's Events",
        "from_yesterday": "from yesterday",
        "needs_attention": "Needs attention",
        "pending": "pending",
        "recent_activity": "Recent Activity",
        "load_more_activities": "Load More Activities",
        "all_activities": "All Activities",
        "today": "Today",
        "this_week": "This Week",
        "this_month": "This Month",
        "all_time": "All Time",
        "new_patients": "New Patients",
        "appointments": "Appointments",
        "alerts": "Alerts",
        "system": "System",
        "new_patient_reg": "New Patient Registered",
        "appt_scheduled": "Appointment Scheduled",
        "new_emp_added": "New Employee Added",
        "monthly_report_gen": "Monthly Report Generated",
        "low_inv_alert": "Low Inventory Alert",
        "appt_completed": "Appointment Completed",
        "patient_rec_updated": "Patient Record Updated",
        "appt_rescheduled": "Appointment Rescheduled",
        "get_started_clinic": "Get Started with Your Clinic",
        "setup_guide": "Add your first patient or set up your medical team to begin managing your practice with elite precision.",
        "setup_staff": "Setup Staff",
        "overview": "Overview",
        "staff": "Staff",
        "admin": "Admin",
        "doctor": "Doctor",
        "nurse": "Nurse",
        "receptionist": "Receptionist",
        "universal_search": "Universal Search...",
        "today_patients": "Today Patients",
        "active_staff": "Active Staff",
        "simulated_live": "Simulated Live Environment",
        "recent_db_hits": "Recent Database Hits",
        "laboratory": "Laboratory",
        "consultation": "Consultation",
        "checkup": "Checkup",
        "in_progress": "In Progress",
        "completed": "Completed",
        // Chat / Other
        "ai_concierge": "AI Concierge",
        "ask_ai": "Ask our AI Concierge",
        "how_assist": "How can I assist you today?",
        "online_ready": "Online & Ready",
        "pricing_fees": "Pricing & Fees",
        "booking_inquiries": "Booking Inquiries",
        "type_inquiry": "Type your inquiry...",
        "showing_page": "Showing Page",
        "of": "of",
        "confirm_delete": "Confirm Delete",
        "delete_confirm_msg": "Are you sure you want to delete this employee? This action cannot be undone.",
        "delete_patient_msg": "Are you sure you want to delete this patient record?",
        "wasender": "WASender",
        "bulk_sender": "Bulk Sender",
        "chats": "Chats",
        "send": "Send",
        "add_to_list": "Add to List",
        "register_as_patient": "Register as Patient",
        "import_excel": "Import Excel",
        "message_template": "Message Template",
        "delay_seconds": "Delay (seconds)",
        "start_sending": "Start Sending",
        "pause_sending": "Pause",
        "stop_sending": "Stop",
        "sent_count": "Sent",
        "failed_count": "Failed",
        "total": "Total",
        "variable_help": "Use {{name}} for patient name",
        "select_patients": "Select Patients",
        "bulk_sending_caution": "Bulk sending may result in account ban. Use with caution.",
        "progress": "Progress",
        "logs": "Logs",
        "clear_logs": "Clear Logs",
        "phone_manual_entry": "Manual Entry (Phone numbers, comma separated)",
        "sales": "Sales",
        "manage_sales_desc": "Track daily sessions, payments, and clinic performance.",
        "today_total": "Today's Total",
        "cash": "Cash",
        "network": "Network",
        "cups_count": "Cups",
        "disease_complaint": "Complaint",
        "no_sales_today": "No sessions recorded today.",
        "monthly_revenue": "Monthly Revenue",
        "monthly_expenses": "Monthly Expenses",
        "net_income": "Net Income",
        "recent_sales": "Recent Sessions",
        "add_sale": "Add Session",
        "add_expense": "Add Expense",
        "select_patient": "Select Patient",
        "patient": "Patient",
        "total_amount": "Total Amount",
        "network_amount": "Network Amount",
        "cash_amount": "Cash Amount",
        "offers_discounts": "Offers/Discounts",
        "notes": "Notes",
        "recorded": "Recorded",
        "edit_sale": "Edit Session",
        "update_sale": "Update Session",
        "updating": "Updating...",
        "date_time": "Date & Time",
        "confirm_delete_sale": "Are you sure you want to delete this session?",
        "sale_updated_success": "Session updated successfully!",
        "sale_recorded_success": "Session recorded successfully!",
    },
    ar: {
        // General
        "portal_access": "دخول البوابة",
        "prof_med_intel": "الذكاء الطبي الاحترافي",
        "access_portal": "دخول البوابة",
        "system_secure_online": "النظام آمن ومتصل",
        "enter_username": "أدخل اسم المستخدم",
        "get_started": "ابدأ الآن",
        "live_experience": "تجربة حية",
        "features": "المميزات",
        "about_us": "من نحن",
        "contact": "اتصل بنا",
        "login": "تسجيل الدخول",
        "logout": "تسجيل الخروج",
        "search_placeholder": "ابحث عن المرضى، الموظفين...",
        "demo": "الديمو",
        "v2_pre_release": "v2.0 إصدار تجريبي",
        "innovation_first": "الابتكار أولاً",
        "core_capabilities": "القدرات الأساسية",
        "experience_edge": "اختبر التميز",
        "interactive_experience": "التجربة التفاعلية",
        "doctors_love": "استكشف الواجهة التي يحبها الأطباء.",
        "operations": "العمليات",
        "support_center": "مركز الدعم",
        "terms_service": "شروط الخدمة",
        "all_rights_reserved": "© 2026 MedCRM Elite Intelligence. جميع الحقوق محفوظة.",
        "global_standards": "معايير الرعاية الصحية العالمية",
        "super_speed": "سرعة فائقة",
        "super_speed_desc": "نظام يعمل في الوقت الفعلي بأداء لا مثيل له لتوفير وقتك.",
        "absolute_security": "أمان مطلق",
        "absolute_security_desc": "تشفير بيانات المرضى على أعلى مستوى من المعايير العالمية.",
        "smart_integration_desc": "ربط مباشر مع الواتساب لتواصل سلس ودائم مع مرضاك.",
        "active_clinic": "عيادة نشطة",
        "customer_satisfaction": "رضا العملاء",
        "doctor_focus": "في رواد الماطي، نؤمن إنك لازم تركز على حلمك، مو على الأوراق. عشان كذا بنينا أنظمة ذكية تدعم نموك بدقة متناهية.",
        "innovators_team": "حنا شركاء نجاحك، نصنع قصة نموك الرقمي من الألف للياء.",
        // Feature Bento Grid
        "feat_bento_title": "طبقة الذكاء الاصطناعي",
        "feat_bento_subtitle": "MedCRM ليس مجرد قاعدة بيانات؛ إنه شريك استباقي في نجاح عيادتك.",
        "feat_unified_inbox_title": "مركز التواصل الموحد",
        "feat_unified_inbox_desc": "استقبل وأدر رسائل واتساب، فيسبوك، وإنستجرام في شاشة مركزية واحدة. لا داعي للتنقل بين التطبيقات.",
        "feat_lead_capture_title": "صيد العملاء الآلي",
        "feat_lead_capture_desc": "حول التعليقات والرسائل إلى عملاء محتملين بضغطة زر. اعرف بالضبط من أين يأتي مرضاك.",
        "feat_archiving_title": "الأرشيف الرقمي الموحد",
        "feat_archiving_desc": "كافة بيانات وتاريخ العملاء في مكان واحد وبوابة عالية الأمان للوصول الفوري.",
        "feat_analytics_title": "تقارير اتخاذ القرار",
        "feat_analytics_desc": "رؤية شاملة للأداء لاتخاذ قرارات طبية وإدارية مبنية على البيانات.",
        "feat_automation_title": "أتمتة العمليات",
        "feat_automation_desc": "قلل العمل اليدوي ووفر الوقت من خلال أتمتة المهام المتكررة والمتابعات.",
        "feat_team_sync_title": "تنسيق الفريق المتميز",
        "feat_team_sync_desc": "ربط المبيعات والتسويق والطاقم الطبي لضمان تجربة مريحة وسلسة للمريض.",
        // Landing Page
        "hero_title_1": "نظام التشغيل المثالي لـ",
        "hero_title_2": "الطب الحديث",
        "hero_subtitle": "ارتقِ بعيادتك من خلال طبقة ذكاء متطورة. أدر المرضى والموظفين والعمليات بدقة وأناقة لا مثيل لها.",
        "trusted_by": "موثوق من قبل مراكز طبية رائدة",
        "features_title": "قوة لا تضاهى، مقدمة ببراعة.",
        "features_subtitle": "MedCRM ليس مجرد أداة؛ إنه ميزة تنافسية لممارستك الطبية.",
        // Features Section
        "feat_patients_title": "إدارة المرضى",
        "feat_patients_desc": "سجلات مرضى مركزية مع التاريخ السريري وتتبع دقيق للبيانات.",
        "feat_staff_title": "الموارد البشرية والطاقم",
        "feat_staff_desc": "تحكم في الوصول وراقب أداء فريقك الطبي المتميز.",
        "feat_localization_title": "ترجمة وتوطين",
        "feat_localization_desc": "دعم كامل للغتين العربية والإنجليزية مع مراعاة اتجاه النص.",
        // About Us
        "about_narrative": "تأسست شركة رواد الماطي لتكون الشريك التقني والتسويقي الأول للمنشآت الطبية والذكية في المملكة العربية السعودية.",
        "about_vision_title": "رؤيتنا",
        "about_vision_desc": "أن نكون العمود الفقري الرقمي لأرقى وأنجح المراكز في المملكة.",
        "about_values_title": "التميز الطبي",
        "about_values_desc": "كل بكسل وسطر برمجية مُحسّن لتحقيق موثوقية طبية فائقة.",
        // Social
        "follow_us": "تابع مستقبل الطب",
        "whatsapp_connect": "خط الواتساب المباشر",
        "instagram_story": "التميز السريري على إنستغرام",
        "telegram_updates": "تحديثات المختبر الآمنة",
        // Dashboard
        "dashboard": "لوحة التحكم",
        "employees": "الموظفين",
        "patients": "المرضى",
        "whatsapp": "واتساب",
        "activity": "النشاط",
        "settings": "الإعدادات",
        // Dashboard Stats
        "total_patients": "إجمالي المرضى",
        "active_employees": "الموظفين النشطين",
        "appointments_today": "مواعيد اليوم",
        "revenue_monthly": "الإيرادات (الشهرية)",
        "revenue_weekly": "الإيرادات (الأسبوعية)",
        "revenue_daily": "الإيرادات (اليومية)",
        "view_all": "عرض الكل",
        "no_recent_activity": "لا توجد نشاطات مسجلة مؤخراً.",
        "welcome_command_center": "مرحباً بك في مركز القيادة الطبي الخاص بك.",
        "intelligence_core": "مركز الذكاء",
        "medical_alerts": "التنبيهات الطبية",
        "no_alerts": "لا توجد تنبيهات عاجلة حالياً.",
        "patient_growth": "نمو المرضى والنشاط",
        "initializing_data": "جاري تهيئة تدفق البيانات...",
        "initializing_data_sub": "يرجى الانتظار بينما نقوم بمزامنة سجلاتك السريرية.",
        // Patients Module
        "patients_title": "المرضى",
        "patients_subtitle": "إدارة سجلات المرضى وتتبع حالتهم الصحية.",
        "search_patients": "ابحث عن المرضى...",
        "patient_list": "قائمة المرضى",
        "add_new_patient": "إضافة مريض جديد",
        "add_patient": "إضافة مريض",
        "edit_patient": "تعديل مريض",
        "patient_details": "تفاصيل المريض",
        "all_types": "كل الأنواع",
        "individual": "فرد",
        "company": "شركة",
        "archive_empty": "الأرشيف فارغ",
        "patient_name": "اسم المريض",
        "patient_type": "نوع المريض",
        "phone_number": "رقم الهاتف",
        "email_address": "البريد الإلكتروني",
        "whatsapp_number": "رقم الواتساب",
        "address": "العنوان",
        "gender": "النوع",
        "male": "ذكر",
        "female": "أنثى",
        "birth_date": "تاريخ الميلاد",
        "status": "الحالة",
        "new": "جديد",
        "admitted": "محجوز",
        "discharged": "خرج",
        "under_treatment": "تحت العلاج",
        "recovered": "تم الشفاء",
        "full_name": "الاسم بالكامل",
        "patient_added_success": "تم إضافة المريض بنجاح!",
        "adding": "جاري الإضافة...",
        "save": "حفظ",
        "chat": "دردشة",
        "details": "التفاصيل",
        // Employees Module
        "employees_title": "الموظفين",
        "employees_subtitle": "إدارة الطاقم الطبي وأفراد الفريق.",
        "search_employees": "ابحث بالاسم، الوظيفة، أو الهاتف...",
        "add_employee": "إضافة موظف",
        "edit_employee": "تعديل موظف",
        "backup_restore": "النسخ الاحتياطي والاستعادة",
        "no_employees_found": "لم يتم العور على موظفين. اضغط 'إضافة موظف' للإنشاء.",
        "role": "الوظيفة",
        "department": "القسم",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "login_credentials": "بيانات الدخول",
        "general_dept": "عام",
        "active": "نشط",
        "inactive": "غير نشط",
        "disable_access": "تعطيل الدخول",
        "enable_access": "تفعيل الدخول",
        "edit_details": "تعديل التفاصيل",
        "employee_added_success": "تم إضافة الموظف بنجاح!",
        "employee_updated_success": "تم تحديث بيانات الموظف بنجاح!",
        "saving": "جاري الحفظ...",
        "backup_mgmt": "إدارة بيانات الموظفين",
        "export_json": "تصدير إلى JSON",
        "import_json": "استيراد من JSON",
        "exporting": "جاري التصدير...",
        "importing": "جاري الاستيراد...",
        "clear_all_employees": "مسح كافة الموظفين",
        "important_notes": "ملاحظات هامة",
        "export_note": "التصدير ينشئ ملف نسخة احتياطية JSON",
        "import_note": "الاستيراد يدمج البيانات (يحدث الموجود ويضيف الجديد)",
        "clear_note": "مسح الكل يحذف كافة الموظفين نهائياً",
        "export_success": "تم تصدير الموظفين بنجاح",
        "import_success": "اكتمل الاستيراد",
        "clear_success": "تم حذف الموظفين",
        "invalid_json": "ملف JSON غير صالح أو فشل الاستيراد",
        // Settings Module
        "settings_title": "الإعدادات",
        "settings_subtitle": "إدارة تفضيلات التطبيق وتكوين النظام.",
        "lang_localization": "اللغة والتوطين",
        "lang_localization_desc": "ضبط اللغة المفضلة والإعدادات الإقليمية.",
        "system_lang": "لغة النظام",
        "choose_pref_lang": "اختر لغة واجهة المستخدم المفضلة لديك",
        "date_format": "تنسيق التاريخ",
        "date_format_us": "شهر/يوم/سنة (الولايات المتحدة)",
        "date_format_eg": "يوم/شهر/سنة (مصر/المملكة المتحدة)",
        "date_format_iso": "سنة-شهر-يوم (ISO)",
        "time_date_settings": "إعدادات الوقت والتاريخ",
        "time_date_desc": "تكوين عرض الوقت وتفضيلات المنطقة الزمنية.",
        "timezone": "المنطقة الزمنية",
        "cairo_tz": "القاهرة (GMT+2) - مصر",
        "utc_tz": "توقيت عالمي (GMT+0)",
        "ny_tz": "نيويورك (EST)",
        "london_tz": "لندن (GMT)",
        "dubai_tz": "دبي (GST)",
        "clock_display": "عرض الساعة",
        "12_hour": "12 ساعة (ص/م)",
        "24_hour": "24 ساعة",
        "notifications": "التنبيهات",
        "notifications_desc": "التحكم في كيفية تلقي التنبيهات والتحديثات.",
        "whatsapp_notif": "تنبيهات الواتساب",
        "whatsapp_notif_desc": "تلقي تذكيرات المواعيد عبر الواتساب",
        "email_notif": "تنبيهات البريد الإلكتروني",
        "email_notif_desc": "تلقي تقارير ملخص يومية عبر البريد الإلكتروني",
        "appearance": "المظهر",
        "appearance_desc": "تخصيص شكل وملمس مساحة العمل الخاصة بك.",
        "theme_mode": "وضع الثيم",
        "light_mode": "الوضع الفاتح",
        "dark_mode": "الوضع المظلم",
        "system_auto": "تلقائي حسب النظام",
        "security_privacy": "الأمن والخصوصية",
        "security_privacy_desc": "إدارة إعدادات أمان حسابك.",
        "change_password": "تغيير كلمة المرور",
        "two_factor": "المصادقة الثنائية",
        "active_sessions": "الجلسات النشطة",
        "data_mgmt": "إدارة البيانات",
        "data_mgmt_desc": "نسخ وإدارة بيانات عيادتك.",
        "export_excel": "تصدير البيانات (Excel)",
        "import_data": "استيراد البيانات",
        "clear_data": "مسح كافة البيانات (خطر)",
        // Form Buttons / UI
        "save_changes": "حفظ التغييرات",
        "cancel": "إلغاء",
        "apply": "تطبيق",
        "confirm": "تأكيد",
        "delete": "حذف",
        "loading": "جاري التحميل...",
        "whatsapp_messages": "رسائل الواتساب",
        "manage_whatsapp_desc": "إدارة استفسارات المرضى ورسائلهم من الواتساب.",
        "open_whatsapp_web": "فتح واتساب ويب",
        "clinic_whatsapp_num": "رقم واتساب العيادة",
        "patients_reach_at": "يمكن للمرضى الوصول إليك على:",
        "open_chat": "فتح الدردشة",
        "total_messages": "إجمالي الرسائل",
        "unread": "غير مقروء",
        "read": "مقروء",
        "avg_response_time": "متوسط وقت الرد",
        "all_messages": "كل الرسائل",
        "unread_only": "غير المقروء فقط",
        "read_only": "المقروء فقط",
        "filter": "تصفية",
        "recent_messages": "الرسائل الأخيرة",
        "reply_on_whatsapp": "رد عبر واتساب",
        "mark_as_read": "تحديد كمقروء",
        "load_more_messages": "تحميل المزيد من الرسائل",
        "whatsapp_api_integrate": "كيفية دمج واجهة برمجة تطبيقات واتساب للأعمال",
        "whatsapp_api_desc": "لاستلام رسائل حقيقية من المرضى، يلزمك دمج واجهة برمجة تطبيقات واتساب للأعمال. اتصل بالمطور لإعداد خطافات الويب (webhooks) وربط هذه الصفحة بحساب واتساب للأعمال الخاص بك.",
        "system_activity": "نشاط النظام",
        "monitor_activity_desc": "مراقبة الإجراءات الأخيرة وأحداث النظام في الوقت الفعلي.",
        "todays_events": "أحداث اليوم",
        "from_yesterday": "منذ الأمس",
        "needs_attention": "يحتاج إلى اهتمام",
        "pending": "قيد الانتظار",
        "recent_activity": "النشاط الأخير",
        "load_more_activities": "تحميل المزيد من الأنشطة",
        "all_activities": "كل الأنشطة",
        "today": "اليوم",
        "this_week": "هذا الأسبوع",
        "this_month": "هذا الشهر",
        "all_time": "كل الوقت",
        "new_patients": "المرضى الجدد",
        "appointments": "المواعيد",
        "alerts": "التنبيهات",
        "system": "النظام",
        "new_patient_reg": "تسجيل مريض جديد",
        "appt_scheduled": "جدولة موعد",
        "new_emp_added": "إضافة موظف جديد",
        "monthly_report_gen": "إنشاء التقرير الشهري",
        "low_inv_alert": "تنبيه نقص المخزون",
        "appt_completed": "اكتمل الموعد",
        "patient_rec_updated": "تحديث سجل المريض",
        "appt_rescheduled": "إعادة جدولة الموعد",
        "get_started_clinic": "ابدأ مع عيادتك",
        "setup_guide": "أضف مريضك الأول أو قم بإعداد فريقك الطبي للبدء في إدارة ممارستك بدقة متناهية.",
        "setup_staff": "إعداد الموظفين",
        "overview": "نظرة عامة",
        "staff": "طاقم العمل",
        "admin": "مدير",
        "doctor": "طبيب",
        "nurse": "ممرض/ة",
        "receptionist": "موظف استقبال",
        "universal_search": "بحث شامل...",
        "today_patients": "مرضى اليوم",
        "active_staff": "الطاقم النشط",
        "simulated_live": "بيئة محاكاة حية",
        "recent_db_hits": "سجلات القاعدة الأخيرة",
        "laboratory": "مختبر",
        "consultation": "استشارة",
        "checkup": "فحص",
        "in_progress": "قيد التنفيذ",
        "completed": "مكتمل",
        // Chat / Other
        "ai_concierge": "المساعد الذكي",
        "ask_ai": "اسأل مساعدنا الذكي",
        "how_assist": "كيف يمكنني مساعدتك اليوم؟",
        "online_ready": "متصل وجاهز",
        "pricing_fees": "الأسعار والرسوم",
        "booking_inquiries": "استفسارات الحجز",
        "type_inquiry": "اكتب استفسارك هنا...",
        "showing_page": "عرض صفحة",
        "of": "من",
        "confirm_delete": "تأكيد الحذف",
        "delete_confirm_msg": "هل أنت متأكد من حذف هذا الموظف؟ لا يمكن التراجع عن هذا الإجراء.",
        "delete_patient_msg": "هل أنت متأكد من حذف سجل هذا المريض؟",
        "data_management": "إدارة البيانات",
        "backup_subtitle": "عمل نسخة احتياطية واستعادة بيانات النظام بأمان.",
        "export_data": "تصدير البيانات",
        "export_desc": "إنشاء نسخة كاملة من سجلات المرضى والموظفين والنشاطات.",
        "import_desc": "استعادة البيانات من ملف نسخة احتياطية سابق.",
        "download_backup": "تحميل النسخة الاحتياطية",
        "restore_data": "استعادة البيانات",
        "restoring": "جاري الاستعادة...",
        "generating": "جاري التحميل...",
        "wasender": "مرسل الرسائل",
        "bulk_sender": "إرسال بالجملة",
        "chats": "المحادثات",
        "send": "إرسال",
        "add_to_list": "إضافة للقائمة",
        "register_as_patient": "تسجيل مريض جديد",
        "import_excel": "استيراد إكسيل",
        "message_template": "قالب الرسالة",
        "delay_seconds": "الفاصل الزمني (ثواني)",
        "start_sending": "بدء الإرسال",
        "pause_sending": "إيقاف مؤقت",
        "stop_sending": "إيقاف",
        "sent_count": "تم الإرسال",
        "failed_count": "فشل",
        "total": "الإجمالي",
        "variable_help": "استخدم {{name}} لاسم المريض",
        "select_patients": "اختر المرضى",
        "bulk_sending_caution": "الإرسال بالجملة قد يؤدي لحظر الحساب. استخدمه بحذر.",
        "progress": "التقدم",
        "logs": "السجلات",
        "clear_logs": "مسح السجلات",
        "phone_manual_entry": "إدخال يدوي (أرقام الهواتف، مفصولة بفاصلة)",
        "sales": "المبيعات",
        "manage_sales_desc": "تتبع الجلسات اليومية، المدفوعات، وأداء العيادة.",
        "today_total": "إجمالي اليوم",
        "cash": "كاش",
        "network": "شبكة",
        "cups_count": "عدد الكاسات",
        "disease_complaint": "الشكوى/المرض",
        "no_sales_today": "لا توجد جلسات مسجلة اليوم.",
        "monthly_revenue": "إيرادات الشهر",
        "monthly_expenses": "مصروفات الشهر",
        "net_income": "صافي الدخل",
        "recent_sales": "آخر الحالات",
        "add_sale": "إضافة حالة",
        "add_expense": "إضافة مصروف",
        "select_patient": "اختر المريض",
        "patient": "المريض",
        "total_amount": "إجمالي المبلغ",
        "network_amount": "مبلغ الشبكة",
        "cash_amount": "مبلغ الكاش",
        "offers_discounts": "العروض/الخصومات",
        "notes": "ملاحظات",
        "recording": "جاري التسجيل...",
        "recorded": "تم التسجيل",
        "edit_sale": "تعديل حالة",
        "update_sale": "تحديث الحالة",
        "updating": "جاري التحديث...",
        "date_time": "الوقت والتاريخ",
        "confirm_delete_sale": "هل أنت متأكد من حذف هذه الحالة؟",
        "sale_updated_success": "تم تحديث الحالة بنجاح!",
        "sale_recorded_success": "تم تسجيل الحالة بنجاح!",
        "expense_title": "بند المصروف",
        "amount": "المبلغ",
        "category": "الفئة",
        "expense_added_success": "تم إضافة المصروف بنجاح!",
        "rent": "إيجار",
        "electricity": "كهرباء",
        "supplies": "أدوات/مستلزمات",
        "other": "أخرى",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    // Load preference from localStorage
    useEffect(() => {
        const saved = localStorage.getItem('medcrm-lang') as Language;
        if (saved && (saved === 'en' || saved === 'ar')) {
            setLanguage(saved);
        }
    }, []);

    // Sync document attributes with language
    useEffect(() => {
        const isRTL = language === 'ar';
        document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
        document.documentElement.setAttribute('lang', language);
        if (isRTL) {
            document.documentElement.classList.add('font-arabic');
        } else {
            document.documentElement.classList.remove('font-arabic');
        }
    }, [language]);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('medcrm-lang', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    const isRTL = language === 'ar';

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, isRTL }}>
            <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : ''} suppressHydrationWarning>
                {children}
            </div>
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
}
